image: "rust:latest"

stages:
    - build
    - test

build:
    stage: build
    script:
        - cargo build --all-features
    
test:
    stage: test
    script:
        - cargo test --all-features
